export default {
    login: 'Login',
    login_failed: 'LOGIN_FAILED',
    loading: 'Loading',
    password: 'Password',
    username: 'Username',
    email: 'Email',
    home: 'Home',
    maps: 'Maps',
    interventions: 'Interventions',
    hydrants: 'Hydrants',
    homeMessage: 'Welcome',
    profile: 'Profile',
    firestation: 'Fire station',
    firetruck: 'Fire trucks',
    profileMessage: 'And this one has a nav, but with a different color than the login.',
    logout: 'Logout',
    firefighters: 'Firefighters',
    no_internet_connection: 'No internet connection!',
    check_internet_connection: 'Check internet connection and try again.',
    alert_session_expired_title: 'Session expired',
    alert_session_expired_message: 'Your session expired. Please signIn again.',
    validator_username_required: 'Username is required',
    validator_password_required: 'Password is required',
};
