export default {
    login: 'Login',
    login_failed: 'LOGIN_FAILED',
    loading: 'Loading',
    password: 'Password',
    username: 'Username',
    email: 'Email',
    home: 'Home',
    maps: 'Maps',
    interventions: 'Interventions',
    hydrants: 'Hydrants',
    homeMessage: 'Welcome',
    profile: 'Profile',
    firestation: 'Fire station',
    firetruck: 'Fire trucks',
    profileMessage: 'And this one has a nav, but with a different color than the login.',
    logout: 'Logout',
    firefighters: 'Firefighters',
    no_internet_connection: 'No internet connection!',
    check_internet_connection: 'Check internet connection and try again.',
    alert_session_expired_title: 'Session expired',
    alert_session_expired_message: 'Your session expired. Please signIn again.',
    validator_username_required: 'Username is required',
    validator_password_required: 'Password is required',

    //////////SHOURTCUT TO CONVERTER
    S: 'interior',
    T: 'back box',
    D: 'roof',
    L1: 'first box on the left',
    L2: 'second box on the left',
    L3: 'third box on the left',
    L4: 'fourth box on the left',
    L5: 'fifth box on the left',
    R1: 'first box on the right',
    R2: 'second box on the right',
    R3: 'third box on the right',
    R4: 'fourth box on the right',
    R5: 'fifth box on the right',

    //////////PROFILE
    firefighterData: 'Firefighter information:',
    currentLocation: 'Yours location:',
    longitude: 'Longitude',
    latitude: 'Latitude',
    altitude: 'Altitude',
    speed: 'Speed',
    accuracy: 'Accuracy',
    address: 'Yours address',
    permissionTitle: 'Location Access Required',
    permissionMessage: 'This App needs to Access your location',
    permissionDenied: 'Permission Denied',
    permissionError: 'Error, cannot get your location',

    //////////FIRE STATION
    fireStationData: 'Fire Station information:',
    fireStationEquipmentsData: 'Fire Station Equipments:',
    numberOfFirefighters: 'Number of firefighters:',
    numberOfInterventions: 'Number of interventions:',
    numberOfFireTrucks: 'Number of fire trucks:',

    //////////FIREFIGHTER
    fireFightersInformation: 'People from your fire unit:',
    phoneNumber: 'Phone number: ',

    //////////FIRE TRUCK
    interventionsInformation: 'Interventions: ',
    timeOfDeparture: 'Time of departure: ',
    arrivalTime: 'ArrivalTime: ',
    firefightersOnAction: 'Firefighters on action: ',
    noFireTruckEquipment: 'No fire truck equipment.',
    searchInputPlaceholder: 'Type a fire truck equipment to search',
};
