export default {
    login: 'Login',
    login_failed: 'LOGIN_FAILED',
    loading: 'Ładowanie',
    password: 'Hasło',
    username: 'Nazwa użytkownika',
    email: 'Email',
    home: 'Home',
    maps: 'Mapy',
    interventions: 'Interwencje',
    hydrants: 'Hydranty',
    homeMessage: 'Witaj',
    profile: 'Profil',
    firestation: 'Remiza strażacka',
    firetruck: 'Wozy strażackie',
    profileMessage: 'And this one has a nav, but with a different color than the login.',
    logout: 'Wyloguj',
    firefighters: 'Strażacy',
    no_internet_connection: 'Brak połączenia z internetem!',
    check_internet_connection: 'Sprawdź połączenie z internetem i spróbuj ponownie.',
    alert_session_expired_title: 'Sesja wygasła',
    alert_session_expired_message: 'Your session expired. Please signIn again.',
    validator_username_required: 'Username jest wymagane',
    validator_password_required: 'Hasło jest wymagane',

    //////////SHOURTCUT TO CONVERTER
    S: 'kabina',
    T: 'tylna skrytka',
    D: 'dach',
    L1: 'pierwsza skrytka z lewej strony',
    L2: 'druga skrytka z lewej strony',
    L3: 'trzecia skrytka z lewej strony',
    L4: 'czwarta skrytka z lewej strony',
    L5: 'piąta skrytka z lewej strony',
    R1: 'pierwsza skrytka z prawej strony',
    R2: 'druga skrytka z prawej strony',
    R3: 'trzecia skrytka z prawej strony',
    R4: 'czwarta skrytka z prawej strony',
    R5: 'piąta skrytka z prawej strony',

    //////////PROFILE
    firefighterData: 'Informacje o strażaku:',
    currentLocation: 'Twoja lokalizacja:',
    longitude: 'Dł. geogr.',
    latitude: 'Szer. geogr.',
    altitude: 'Wysokość',
    speed: 'Prędkość',
    accuracy: 'Dokładność',
    address: 'Twój adres',
    permissionTitle: 'WYmagany dostęp do lokazliacji',
    permissionMessage: 'Ta aplikacja musi mieć dostęp do Twojej lokalizacji\n',
    permissionDenied: 'Odmowa dostępu',
    permissionError: 'Błąd, nie można uzyskać Twojej lokalizacji',
    modalTitle: 'Potwierdź udział w akcji!',
    actionTypeTitle: 'POŻAR',
    confirm: 'potwierdź',
    discard: 'odrzuć',

    //////////FIRE STATION
    fireStationData: 'Informacje o OSP:',
    fireStationEquipmentsData: 'Sprzęt strażacki:',
    numberOfFirefighters: 'Liczba strażaków:',
    numberOfInterventions: 'Liczba interwencji:',
    numberOfFireTrucks: 'Liczba samochodów pożarniczych:',

    //////////FIREFIGHTER
    fireFightersInformation: 'Osoby z Twojej jednostki:',
    phoneNumber: 'Numer telefonu: ',

    //////////FIRE TRUCK
    interventionsInformation: 'Interwencje: ',
    timeOfDeparture: 'Czas wyjazdu: ',
    arrivalTime: 'Czas powrotu: ',
    firefightersOnAction: 'Strażacy na akcji: ',
    noFireTruckEquipment: 'Brak sprzetu na samochodzie.',
    searchInputPlaceholder: 'Wyszukaj sprzęt...',
};
